<?php
/**
 * Copyright © MagenX. All rights reserved.
 * SPDX-License-Identifier: MIT
 */

declare(strict_types=1);

namespace Magenx\Platform\Test\Unit\Standalone;

use Magenx\Platform\Model\Collector\Nginx;
use Magenx\Platform\Model\Collector\OpenSearch;
use Magenx\Platform\Model\Collector\Php;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

/**
 * The pure private helpers inside the collectors.
 *
 * Reached by reflection rather than through collect(), deliberately. Every one
 * of these is a total function of its arguments that touches no collaborator,
 * so calling it needs no test doubles at all — and going through collect()
 * would need a mocked ResultFactory, which is generated by Magento at compile
 * time and does not exist as a file to mock in a bare checkout.
 *
 * They are pinned because each encodes a decision the source defends at length,
 * and a decision defended only by a comment is one careless edit from silently
 * reverting.
 */
#[CoversClass(Nginx::class)]
#[CoversClass(OpenSearch::class)]
#[CoversClass(Php::class)]
class PrivateParsingTest extends TestCase
{
    /**
     * Call a private method without constructing the collector.
     *
     * @param class-string $class
     * @param string $method
     * @param array $arguments
     * @return mixed
     */
    private function call(string $class, string $method, array $arguments): mixed
    {
        $reflection = new ReflectionClass($class);
        $instance = $reflection->newInstanceWithoutConstructor();
        $callable = $reflection->getMethod($method);
        $callable->setAccessible(true);

        return $callable->invokeArgs($instance, $arguments);
    }

    public function testNginxParsesStubStatusOutput(): void
    {
        $body = "Active connections: 291 \n"
            . "server accepts handled requests\n"
            . " 16630948 16630948 31070465 \n"
            . "Reading: 6 Writing: 179 Waiting: 106 \n";

        $this->assertSame(
            [
                'active' => 291,
                'accepts' => 16630948,
                'handled' => 16630948,
                'requests' => 31070465,
                'reading' => 6,
                'writing' => 179,
                'waiting' => 106,
            ],
            $this->call(Nginx::class, 'parse', [$body])
        );
    }

    public function testNginxSeparatesAcceptsFromHandled(): void
    {
        // The gap between the two is the whole reason this tab exists: nginx
        // only fails to handle a connection it accepted when it has hit
        // worker_connections, and nothing else in the stack reports that.
        $stats = $this->call(
            Nginx::class,
            'parse',
            [
                "Active connections: 1 \nserver accepts handled requests\n 100 97 500 \n"
                . "Reading: 0 Writing: 1 Waiting: 0 \n",
            ]
        );

        $this->assertSame(100, $stats['accepts']);
        $this->assertSame(97, $stats['handled']);
    }

    public function testNginxRejectsAnythingThatIsNotStubStatus(): void
    {
        $this->assertNull($this->call(Nginx::class, 'parse', ['<html><body>404</body></html>']));
        $this->assertNull($this->call(Nginx::class, 'parse', ['']));
        // A JSON status page from something else on that port.
        $this->assertNull($this->call(Nginx::class, 'parse', ['{"active":1}']));
    }

    #[DataProvider('baseUrlProvider')]
    public function testSearchBaseUrl(string $host, int $port, string $expected): void
    {
        $this->assertSame($expected, $this->call(OpenSearch::class, 'buildBaseUrl', [$host, $port]));
    }

    public static function baseUrlProvider(): array
    {
        return [
            // There is no scheme field in the search configuration, so this has
            // to match what Magento's own client does or the tab reports a
            // cluster unreachable that Magento talks to happily.
            'bare host defaults to http' => ['opensearch', 9200, 'http://opensearch:9200'],
            'a scheme in the host wins' => ['https://opensearch', 9200, 'https://opensearch:9200'],
            'scheme case is normalised' => ['HTTPS://opensearch', 9200, 'https://opensearch:9200'],
            // No scheme given, but a port that is only ever TLS in practice.
            'port 443 implies https' => ['opensearch', 443, 'https://opensearch:443'],
            'port 9243 implies https' => ['opensearch', 9243, 'https://opensearch:9243'],
            // A port already written into the hostname wins over the port field.
            'port in the host wins' => ['http://opensearch:9200', 9300, 'http://opensearch:9200'],
            'no port field at all' => ['opensearch', 0, 'http://opensearch'],
            'trailing slash is dropped' => ['http://opensearch/', 9200, 'http://opensearch:9200'],
        ];
    }

    #[DataProvider('userInfoProvider')]
    public function testSearchHostCredentialsAreSplitOff(string $host, array $expected): void
    {
        // A docker-compose stack commonly carries the credentials in the host
        // setting itself, and the endpoint row is not a place to publish a
        // password.
        $this->assertSame($expected, $this->call(OpenSearch::class, 'splitUserInfo', [$host]));
    }

    public static function userInfoProvider(): array
    {
        return [
            'user and password' => ['http://user:secret@opensearch', ['http://opensearch', 'user', 'secret']],
            'user only' => ['http://user@opensearch', ['http://opensearch', 'user', '']],
            'no scheme' => ['user:secret@opensearch', ['opensearch', 'user', 'secret']],
            'nothing to split' => ['http://opensearch', ['http://opensearch', '', '']],
            'bare host' => ['opensearch', ['opensearch', '', '']],
        ];
    }

    #[DataProvider('plaintextSecretProvider')]
    public function testAPlaintextSearchPasswordIsNotHandedToDecrypt(string $stored, string $expected): void
    {
        // A password locked into app/etc/env.php by deployment tooling is
        // stored in clear, and decrypt() answers an empty string for it — which
        // authenticates as nobody and looks exactly like the module ignoring
        // the settings. Only a value shaped like a Magento ciphertext,
        // "<keyVersion>:<cryptVersion>:<payload>", is decrypted, which is why
        // this path needs no encryptor at all.
        $this->assertSame($expected, $this->call(OpenSearch::class, 'readSecret', [$stored]));
    }

    public static function plaintextSecretProvider(): array
    {
        return [
            'empty' => ['', ''],
            'plain' => ['sekrit', 'sekrit'],
            // Testing the shape rather than the result keeps a plaintext
            // password that happens to contain a colon intact.
            'colons survive' => ['pa:ss:word', 'pa:ss:word'],
            'a leading number is not a key version' => ['1password', '1password'],
            'two numbers are not enough' => ['1:2', '1:2'],
        ];
    }

    #[DataProvider('iniSizeProvider')]
    public function testPhpIniShorthandSizes(string $value, int $expected): void
    {
        $this->assertSame($expected, $this->call(Php::class, 'toBytes', [$value]));
    }

    public static function iniSizeProvider(): array
    {
        return [
            'kilobytes' => ['4096k', 4194304],
            'uppercase kilobytes' => ['4096K', 4194304],
            'megabytes' => ['16M', 16777216],
            'gigabytes' => ['1G', 1073741824],
            'a bare byte count' => ['4194304', 4194304],
            'empty' => ['', 0],
            'whitespace' => ['  16M  ', 16777216],
        ];
    }
}
